name: mqlint
version: 0.1.0
license: MIT
author: "Davis Haupt & Yingxuan Eng"
github: "eyingxuan/mqlint"
copyright: "2020 Davis Haupt & Yingxuan Eng"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
  - base >= 4.7 && < 5
  - containers
  - parsec
  - mtl
  - pretty
  - dlist

library:
  source-dirs: src
  ghc-options:
    - -fwarn-incomplete-patterns

executables:
  mqlint-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mqlint

tests:
  mqlint-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mqlint
      - QuickCheck
      - tasty
      - tasty-golden
      - filepath
      - bytestring
      - HUnit
